### ISSUE TITLE
uninitialized constant Cream::Rails::Application (NameError) 

### ISSUE THREAD

**Issue by stefanobernardi** [kristianmandrup/cream#10]
```
rails new cream --skip-active-record
```

put gem 'cream' in my Gemfile

```
bundle install
```

and then rails g gives me:

```
sb:cream sb$ rails g
/Users/sb/Sites/cream/config/application.rb:10:in `<module:Cream>': uninitialized constant Cream::Rails::Application (NameError)
    from /Users/sb/Sites/cream/config/application.rb:9:in `<top (required)>'
    from /Users/sb/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:15:in `require'
    from /Users/sb/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.4/lib/rails/commands.rb:15:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by kristianmandrup** [comment]
Try and do the same steps but don't call your application 'Cream'. That will just conflict with the toplevel Cream namespace, causing all kinds of trouble.
Instead try fx 

rails new cream-app --skip-active-record

Let me know if you still have problems, and posting on the cream google group is better for troubleshooting ;)

**Comment by stefanobernardi** [comment]
I'm an idiot. Sorry about that, thanks for the quick reply, will use the group for future things :)
