### ISSUE TITLE
Out of the box error? (Guest user)

### ISSUE THREAD

**Issue by elcuervo** [kristianmandrup/cream#11]
Hello, i've been testing Cream and configuring a rails3 app out of the box i've got this:
Should i have to generate a migration for a guest user?

NameError Exception: undefined local variable or method `session' for Guest(Table doesn't exist):Class

**Comment by kristianmandrup** [comment]
Cream expects a model Guest that is a guest user. Check out the wiki page about it.
Oh, I recently added the concept of Devise "User Types" to the mix, whereas before it only used roles. Therefor the default roles no longer produces the default Devise user types...! Sorry! Got to fix that ASAP ;)

**Comment by narojigautam** [comment]
I have faced this problem too :( . Any updates on this yet?

**Comment by kristianmandrup** [comment]
Oh yeah, I gotta get cream up and working again by debugging and testing it. Been away skiing for a while, just came back.

**Comment by kristianmandrup** [comment]
Cream updated to work again. Guest should not have a table, hence no migration.

**Comment by narojigautam** [comment]
Thank You Kristian.
