### ISSUE TITLE
Installing Cream gem fails

### ISSUE THREAD

**Issue by benlangfeld** [kristianmandrup/cream#13]
{13:34}[ruby-1.9.2@creamtest]~/Desktop/creamtest@master✗✗✗ ben% gem install cream
ERROR:  While executing gem ... (Gem::Exception)
    ruby_code case not handled: Syck::PrivateType

**Comment by kristianmandrup** [comment]
Yes, I struggled with this a lot the past week or so. Had to do with ruby 1.9.2 compatibility problems with psych (replacing old yaml parser) and Rubygems 1.5.
I had to delete and reinstall my ruby 1.9.2 and then install Rubygems 1.5.2.
Hope that works out for you!

**Comment by benlangfeld** [comment]
Ah, I was still on rubygems 1.3.7. An update to 1.5.2 worked for me :)
