### ISSUE TITLE
Can not Bundle 'Cream' - ruby_code case not handled: Syck::PrivateType

### ISSUE THREAD

**Issue by Arisey** [kristianmandrup/cream#16]
Is this gem private?

**Comment by kristianmandrup** [comment]
I know, I have to fix that. Somehow after changing to Rubygems 1.5 it has been a bit messed up, due to the YAML parser being replaced by Psych. I will work on that in the coming days. I've had no time until now.

**Comment by Arisey** [comment]
Thanks for your kind help.  Look forward to using this gem soon.

**Comment by matellis** [comment]
Any idea when this issue will be fixed? It's preventing us from deploying to Heroku with Cream. Can't find a way to make it work either. Thx.

**Comment by kristianmandrup** [comment]
I am so sorry about this. I think it has something to do with the current gemspec which is configured using the "old" Jeweler? I will try reworking the gems today. Hopefully all will be running smoothly by tomorrow afternoon GMT at the latest. Sorry to keep you waiting.

**Comment by kristianmandrup** [comment]
I am sorry, it is more complexand is taking longer than I imagined. Cream should also work with rubygems < 1.5 for now. Not sure if that is acceptable?
I'm working on it!

**Comment by whatupdave** [comment]
You can make this work by adding:

```
YAML::ENGINE.yamler = 'syck' 
```

to the .gemspec

**Comment by kristianmandrup** [comment]
I suggest that anyone who has problems with cream take a look at the new cantango gem I have been developing with @stanislaw during the past 2 months. It is much more well designed from the ground up, almost full test coverage, 2 dummy apps for integration tests (with and without devise) and wiki shaping up (currently only as part of source).

https://github.com/kristianmandrup/cantango/

Also Troles will be the new roles gem https://github.com/kristianmandrup/troles

Plan to finish that soon as well ;)

You are most welcome to support these projects in any way you can! Thanks!
