### ISSUE TITLE
gem install cream fails on rvm 1.9.2 + rubygems 1.5.3

### ISSUE THREAD

**Issue by Minger** [kristianmandrup/cream#17]
I got bounced here by the rvm people.

system ruby 1.9.2dev (2010-07-02) [x86_64-linux] + rubygems 1.5.3
installs cream OK.

rvm ruby 1.8.7 + rubygems 1.5.3
installs cream OK.

rvm ruby 1.9.2 + rubygems 1.5.3
ERROR:  While executing gem ... (ArgumentError)
    undefined class/module YAML::PrivateType

even if i regenerate cream.gemspec and build cream (0.8.9.2) with rubygems 1.5.3, I get the same error.

**Comment by kristianmandrup** [comment]
Yes, I have the same issue. I have yet to uncover what causes the problem. It seems there is some problem with nested dependency structures. I'm working on it.

**Comment by kristianmandrup** [comment]
after a long struggle I have released new versions of all (or most) of the gems that cream depends on and also release a new version of cream itself. Now it should install with Rubygems 1.6+ and Ruby 1.9.2 on RVM. Please test it out and let me know of any issues/problems still occurring. Note I have also updated Roles for AR and Mongoid, but not yet for the other ORMs.

**Comment by Minger** [comment]
Kristian,  thanks for the effort.  gem install devise-links (required by cream) fails with the same error as reported.

**Comment by drl123** [comment]
I am having the same issue with the YAML error.  I tried removing Ruby 1.9.2 and re-installing Rubygems 1.6.1 and Ruby 1.9.2 (deleted old directories first to make sure there were no remnants), but still get the YAML error and only on devise-links gem.  The other gems seemed to install OK.  This is the last gem keeping me from getting Cream installed.  Any advice?  I'm very anxious to try it as it looks like exactly what I need.

**Comment by Minger** [comment]
I would suggest installing cream on ruby 1.8.7 until Kristian fixes the problem.

**Comment by kristianmandrup** [comment]
Ah, well, it installs for me locally now. Maybe I forgot to pusblish one or two gems that cream depends on. Basically I had to regenerate the gemspecs for all gems and such. I can see that I somehow forgot to add the gemspec for devise-links. Will add it and push the new release now ;) Hope that helps or gets you further.

**Comment by kristianmandrup** [comment]
I have been skiing for the past week, and only today got online again. Are you still having problems installing cream?

**Comment by Minger** [comment]
Your 3/4 commits installed with no problems.  Thanks!

**Comment by jits** [comment]
Unfortunately, the gem (last updated March 3rd 2011) still errors with this problem.

My environment: Ubuntu x86, RVM, Ruby 1.9.2, RubyGems 1.6.2

I'll try and take a closer look.

Any help will be greatly appreciated!

Jits

**Comment by kristianmandrup** [comment]
Yeah, sorry, I really should look into it! Just been too busy lately...

**Comment by jits** [comment]
Not a problem; I understand how it goes :)

Do let us know when you have a solution, or need help.

Jits

**Comment by Minger** [comment]
Does it install in your system Ruby?

Did you try deleting rvm 1.9.2 and trying it again with a clean installation?
