### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by CameronGilroy** [kristianmandrup/cream#20]
Hi I am getting a strange error when I run "bundle install" not sure what is going on.
Here is the error.

Installing migration_assist (0.1.9) /Users/cameron/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/specification.rb:1050:in `ruby_code': ruby_code case not handled: Syck::PrivateType (Gem::Exception)
        from /Users/cameron/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/specification.rb:762:in`block in to_ruby'
        from /Users/cameron/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/specification.rb:757:in `each'
        from /Users/cameron/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/specification.rb:757:in`to_ruby'
        from /Users/cameron/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/installer.rb:260:in `write_spec'
        from /Users/cameron/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/installer.rb:199:in`install'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/source.rb:95:in `install'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/installer.rb:55:in`block in run'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/spec_set.rb:12:in `block in each'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/spec_set.rb:12:in`each'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/spec_set.rb:12:in `each'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/installer.rb:44:in`run'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/installer.rb:8:in `install'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/cli.rb:225:in`install'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/vendor/thor/task.rb:22:in `run'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/vendor/thor/invocation.rb:118:in`invoke_task'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/vendor/thor.rb:246:in `dispatch'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/vendor/thor/base.rb:389:in`start'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/bin/bundle:13:in `<top (required)>'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/bin/bundle:19:in`load'
        from /Users/cameron/.rvm/gems/ruby-1.9.2-p0/bin/bundle:19:in `<main>'

hope this helps and is in the correct place .

Thanks,

**Comment by TouriM** [comment]
The migration_assist in version 0.1.9 is broken. But there is a newer version 0.2. That one should work.

**Comment by kristianmandrup** [comment]
Hi guys! I'm finally back from China. I expect to have some time to fix any remaining issues in the very near future.

**Comment by TouriM** [comment]
That is good to know. 
Hope you have had a good time in China. 
Thanks!

**Comment by cies** [comment]
i got this error too...
indeed this fixed it all:

<code>gem install migration_assist</code>

**Comment by kristianmandrup** [comment]
I think this adding this to the Rakefile of _roles_active_record_ might fix it:

```
gem.add_development_dependency 'migration_assist',  '~> 0.2.0'
```

_roles_active_record_ seems to install fine using rubygems 1.7.2 for me with this fix. I had a lot of trouble making cream work with rubygems 1.5 and 1.6, but now seems more stable. If you concur that this fix works in your environment I will add it as a patch to next release of roles_active_record.

**Comment by kristianmandrup** [comment]
I just pushed a _migration_assist_ branch of _roles_active_record_ with the fix mentioned in the previous comment.

**Comment by airios** [comment]
I'm getting the same error.
The following does not work for me:
`gem install migration_assist`

rvm - ruby 1.9.2

**Comment by kristianmandrup** [comment]
I just tried installing migration_assist locally using rubygems 1.8.2 and RVM  with ruby 1.9.2.p136

$ ruby -v
ruby 1.9.2p136 (2010-12-25 revision 30365) [x86_64-darwin10.6.0]

$ gem -v
1.8.0

$ gem install migration_assist
Successfully installed migration_assist-0.2.0
1 gem installed
Installing ri documentation for migration_assist-0.2.0...
Building YARD (yri) index for migration_assist-0.2.0...
Installing RDoc documentation for migration_assist-0.2.0...

Which rubygems and RVM versions are you using?

**Comment by airios** [comment]
Works now. Just needed to force rvm to listen:
`$ ruby -v`
`ruby 1.9.2p180`
`$ gem -v`
`1.6.2`

Thanks!

**Comment by kristianmandrup** [comment]
Great! I recommend you upgrade your rubygems to 1.8.0

$ gem update --system

Then follow the instructions to clean up your existing gemspecs ;)
