### ISSUE TITLE
Can you please release a new roles_mongo_mapper?

### ISSUE THREAD

**Issue by leefaus** [kristianmandrup/cream#28]
I have this installed on my mac where psych is not installed, only syck.  On my staging server, I get both psych and syck for the YAML parser.  When I try to install roles_mongo_mapper I get 

[axial@343992-app1 axialalertsv2]$ gem install roles_mongo_mapper
ERROR:  While executing gem ... (ArgumentError)
    undefined class/module YAML::PrivateType

I have been working on this for over 4 hours with help from the rubygems irc room.  Any help is greatly appreciated.

gem -v = 1.5.2
ruby -v = 1.9.2p180

using rvm.

**Comment by kristianmandrup** [comment]
I will see what I can do. Another option for you, would be to use the https://github.com/kristianmandrup/troles gem. It should be pretty easy to create an adapter for mongo mapper. It sports a much better, cleaner design and is much easier to adapt to other data stores. Also check out the cream google group. I'm currently working with @stanislaw on a replacement for cancan-permits called _tango_ which is almost ready for release. Then we plan to release a fresh replacement for cream called _dancing_. You are most welcome to help out if you are interested! 
I will see if I can release a new roles_mongo_mapper without this YAML error. I think it requires regeneration of the gemspec file etc.

**Comment by kristianmandrup** [comment]
Please try the latest release of roles_mongo_mapper 0.4.1, now with updated dependencies ;)

**Comment by leefaus** [comment]
i made some other modifications to the spec as there were duplicates for dependencies.  i also ran into some issues one of the dependencies.  I am interested in your future work and take a deeper look once this iteration makes it to production.  thanks for the help

**Comment by kristianmandrup** [comment]
Sounds good :) Please give me a pull request on any fixes u make.
Check out tango at: https://github.com/stanislaw/tango/commits/permission_store/
We are moving quickly...
Cheers!
