### ISSUE TITLE
Rails 3.1.0.rc4 support

### ISSUE THREAD

**Issue by X4** [kristianmandrup/cream#29]
Hi Kristian,

that's a damn fine thing you've developed there, really.
I've just spent an hour solving a dependancy issue with sugar-high, then the resuls was that I couldn't start your app because I was using Rails 3.1.0.rc4 and you've hardcoded 3.01 which is sad :( at least for me..

however hope you got the time and can add Rails 3.1.0.rc4 support some time, that would really rock!

Thanks

**Comment by kristianmandrup** [comment]
Hi ;) Thanks! The project is currently a little outdated. 
I've recently upgrade sugar-high to 0.5 and the supporting gems to use the 0.5. I can imagine that cream doesn't currently reflect this upgrade! You are most welcome to post me pull request or similar with your dependency fixes!
I am currently working with @stanislaw on a project called "cantango", which is meant to replace cream. 
We are getting close to a first release! I will see if I can relax the cream  - Rails 3.01 condition shortly, to be >= 3.01 instead.
Cheers!

Kristian

**Comment by kristianmandrup** [comment]
I just pushed updated dependencies and rakefile now using Gemfile, to master branch. Hope that helps...
might be other dependency issues in supporting gems? Pls let me know.
