### ISSUE TITLE
full_config generator adding gem 'cream' to Gemfile

### ISSUE THREAD

**Issue by ticktricktrack** [kristianmandrup/cream#6]
I don't really see a need to add 
    gem "cream"
again, since it's a prequisite to running rails generate cream in the first place.

Also, when the Gemfile ends with "end", it's appended direcly after 'd'
    endgem "cream"

**Comment by kristianmandrup** [comment]
Yeah, this is an issue with the Thor _gem_ action. I tried adding a _clean_gemfile_ method to ensure this would be "cleaned up", but I guess it still needs some work.
Which version of Cream are you using? 0.8.1 is the latest.

<pre>
def devise_gems 
  ...
  clean_gemfile        
  bundle_install
end
</pre>


in rails3_assist: special.rb

<pre>
def clean_gemfile
  clean_gemfile_content = read_gem_file.gsub(/('|")\s*gem/m, "\\1\ngem")
  File.open(gem_file, 'w') {|f| f.write(clean_gemfile_content) }
end
</pre>


I guess it should be sth like:

<pre>gsub(/('|"|end)\s*gem/m, "\\1\ngem")</pre>


Ok, fixed this in the latest release of rails3_assist (0.3.3) including spec

**Comment by kristianmandrup** [comment]
has now been fixed in rails3_assist 0.3.3. Please experiment a little and let me know what you think are the minimal required gem additions to the Gemfile :) Thanks!

**Comment by kristianmandrup** [comment]
Fixed. Next release will remove the extra add_gem 'cream' from the generator!
